logging:
    file:
        name: /logs/FarmStory.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
server:
    port: 8080
spring:
    application:
        name: FarmStory
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/farmstory
        username: root
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ppyyhh3285@gmail.com
        password: fbax fmxo pxup eook
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB
    security:
        oauth2:
            client:
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://accounts.google.com/o/oauth2/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: name
                registration:
                    google:
                        client-id: 60431749569-m5e000jb59uqkinlqo5udh3m54d5mlgk.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8080/login/oauth2/code/google
                        scope:
                            - email
                            - profile